class Error:
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    MISSING_PARAMETERS = "MISSING_PARAMETERS"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DATA_NOT_FOUND = "DATA_NOT_FOUND"
    START_DATE_LESSER_THAN_END_DATE = "START_DATE_LESSER_THAN_END_DATE"
    END_DATE_GREATER_THAN_START_DATE = "END_DATE_GREATER_THAN_START_DATE"
